import React, { useState } from 'react';
import { api } from '../../services/api';
import { FileText, X, Loader2, Download, ChevronRight, Shield, Printer } from 'lucide-react';

interface IntelligenceBriefProps {
  userId: string;
  role: string;
  sessionSummary?: string;
  topFindings?: string[];
}

export const IntelligenceBrief: React.FC<IntelligenceBriefProps> = ({
  userId, role, sessionSummary, topFindings = []
}) => {
  const [showModal, setShowModal] = useState(false);
  const [briefTitle, setBriefTitle] = useState('KSP Crime Intelligence Brief');
  const [briefPeriod, setBriefPeriod] = useState(() => {
    const d = new Date(); const m = d.toLocaleString('default', { month: 'long' });
    return `${m} ${d.getFullYear()}`;
  });
  const [approvingOfficer, setApprovingOfficer] = useState('');
  const [classification, setClassification] = useState<'RESTRICTED' | 'CONFIDENTIAL' | 'SECRET'>('RESTRICTED');
  const [customFindings, setCustomFindings] = useState(
    topFindings.length > 0 ? topFindings.join('\n') : ''
  );
  const [keyRecs, setKeyRecs] = useState('');
  const [generating, setGenerating] = useState(false);
  const [previewMode, setPreviewMode] = useState(false);

  const buildBriefHtml = () => {
    const findings = customFindings.split('\n').filter(Boolean);
    const recs = keyRecs.split('\n').filter(Boolean);
    const ts = new Date().toLocaleString('en-IN', { dateStyle: 'long', timeStyle: 'short' });

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${briefTitle}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap');
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Inter',sans-serif; background:#fff; color:#1e293b; padding:40px; max-width:794px; margin:auto; }
  .header { display:flex; align-items:center; justify-content:space-between; padding-bottom:16px; border-bottom:3px solid #0f172a; }
  .ksp-logo { font-size:22px; font-weight:800; color:#0f172a; letter-spacing:-0.5px; }
  .ksp-logo span { color:#10b981; }
  .classification { font-size:11px; font-weight:700; letter-spacing:2px; text-transform:uppercase; padding:4px 12px; border-radius:4px; }
  .RESTRICTED { background:#fef3c7; color:#92400e; border:1px solid #fde68a; }
  .CONFIDENTIAL { background:#fce7f3; color:#9d174d; border:1px solid #fbcfe8; }
  .SECRET { background:#fecaca; color:#7f1d1d; border:1px solid #fca5a5; }
  h1 { font-size:26px; font-weight:800; margin:24px 0 4px; color:#0f172a; }
  .meta-row { display:flex; gap:24px; margin:8px 0 24px; font-size:12px; color:#64748b; }
  .meta-row strong { color:#334155; }
  .section { margin:24px 0; }
  .section-title { font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:1.5px; color:#64748b; border-bottom:1px solid #e2e8f0; padding-bottom:6px; margin-bottom:12px; }
  .finding { display:flex; align-items:flex-start; gap:10px; margin:8px 0; font-size:13px; }
  .bullet { width:6px; height:6px; border-radius:50%; background:#10b981; margin-top:5px; flex-shrink:0; }
  .narrative-box { background:#f8fafc; border:1px solid #e2e8f0; border-radius:6px; padding:14px; font-size:13px; line-height:1.7; color:#334155; }
  .rec { display:flex; align-items:flex-start; gap:10px; margin:8px 0; font-size:13px; }
  .rec-num { width:20px; height:20px; border-radius:50%; background:#0f172a; color:#fff; font-size:10px; font-weight:700; display:flex; align-items:center; justify-content:center; flex-shrink:0; margin-top:1px; }
  .footer { margin-top:40px; padding-top:16px; border-top:2px solid #e2e8f0; display:flex; justify-content:space-between; align-items:flex-end; font-size:11px; color:#94a3b8; }
  .sign-block { text-align:center; }
  .sign-line { width:180px; border-bottom:1px solid #334155; margin-bottom:4px; height:28px; }
  .sign-name { font-weight:700; color:#1e293b; font-size:12px; }
  .watermark { position:fixed; top:50%; left:50%; transform:translate(-50%,-50%) rotate(-35deg); font-size:80px; font-weight:900; color:rgba(15,23,42,0.04); pointer-events:none; text-transform:uppercase; letter-spacing:10px; }
</style>
</head>
<body>
<div class="watermark">OFFICIAL</div>
<div class="header">
  <div class="ksp-logo">KSP <span>INTEL</span></div>
  <span class="classification ${classification}">${classification}</span>
</div>
<h1>${briefTitle}</h1>
<div class="meta-row">
  <div><strong>Reference Period:</strong> ${briefPeriod}</div>
  <div><strong>Generated By:</strong> ${userId} (${role})</div>
  <div><strong>Date &amp; Time:</strong> ${ts}</div>
</div>
${sessionSummary ? `
<div class="section">
  <div class="section-title">Intelligence Narrative</div>
  <div class="narrative-box">${sessionSummary.replace(/\n/g, '<br>')}</div>
</div>` : ''}
${(findings || []).length > 0 ? `
<div class="section">
  <div class="section-title">Key Findings</div>
  ${(findings || []).map(f => `<div class="finding"><div class="bullet"></div><div>${f}</div></div>`).join('')}
</div>` : ''}
${(recs || []).length > 0 ? `
<div class="section">
  <div class="section-title">Recommendations</div>
  ${(recs || []).map((r, i) => `<div class="rec"><div class="rec-num">${i+1}</div><div>${r}</div></div>`).join('')}
</div>` : ''}
<div class="footer">
  <div>
    Karnataka State Police — Intelligence Division<br/>
    This document is classified and intended for official use only.
  </div>
  <div class="sign-block">
    <div class="sign-line"></div>
    <div class="sign-name">${approvingOfficer || role}</div>
    <div style="color:#94a3b8;font-size:10px">Approving Officer</div>
  </div>
</div>
</body>
</html>`;
  };

  const handleDownload = async () => {
    setGenerating(true);
    try {
      const html = buildBriefHtml();
      let blob: Blob;
      try {
        blob = await api.exportPdfReport(html, userId, role);
      } catch {
        // Fallback: download as HTML if PDF service unavailable
        blob = new Blob([html], { type: 'text/html' });
      }
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const ext = blob.type.includes('html') ? 'html' : 'pdf';
      a.setAttribute('download', `KSP-Intelligence-Brief-${Date.now()}.${ext}`);
      document.body.appendChild(a);
      a.click();
      a.parentNode?.removeChild(a);
      setShowModal(false);
    } catch (err) {
      console.error(err);
      alert('Failed to generate Intelligence Brief.');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <>
      <button
        onClick={() => setShowModal(true)}
        id="intelligence-brief-trigger"
        className="flex items-center gap-1.5 px-3 py-1.5 bg-[#1e3a5f]/10 hover:bg-[#1e3a5f]/20 border border-[#1e3a5f]/30 text-white rounded-lg text-xs font-bold transition cursor-pointer"
      >
        <FileText size={13} /> Generate Brief
      </button>

      {showModal && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-[#0d2137]/90 backdrop-blur-sm p-4 overflow-y-auto">
          <div className="w-full max-w-2xl bg-[#f0f4f8] border border-[#d1d9e6] rounded-2xl shadow-2xl my-4">
            {/* Modal Header */}
            <div className="flex justify-between items-center px-6 py-4 border-b border-[#d1d9e6]">
              <h3 className="text-base font-bold text-[#1e3a5f] flex items-center gap-2">
                <Shield size={16} className="text-[#1e3a5f]" />
                Intelligence Brief Generator
              </h3>
              <button onClick={() => setShowModal(false)} className="text-[#6c757d] hover:text-[#1e3a5f] cursor-pointer transition">
                <X size={15} />
              </button>
            </div>

            {/* Tab toggle: form / preview */}
            <div className="flex border-b border-[#d1d9e6]">
              {(['Form', 'Preview'] as const).map(tab => (
                <button key={tab} onClick={() => setPreviewMode(tab === 'Preview')}
                  className={`flex-1 py-2.5 text-xs font-bold transition cursor-pointer ${previewMode === (tab === 'Preview') ? 'text-[#1e3a5f] border-b-2 border-[#1e3a5f]' : 'text-[#6c757d] hover:text-[#2d4a6f]'}`}>
                  {tab}
                </button>
              ))}
            </div>

            {previewMode ? (
              /* Live Preview */
              <div className="p-4 max-h-[60vh] overflow-y-auto">
                <iframe
                  srcDoc={buildBriefHtml()}
                  className="w-full h-[500px] bg-white rounded-lg border border-[#d1d9e6]"
                  title="Brief Preview"
                />
              </div>
            ) : (
              /* Form fields */
              <div className="p-6 space-y-5">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-[#6c757d] mb-1.5">Brief Title</label>
                    <input type="text" value={briefTitle} onChange={e => setBriefTitle(e.target.value)}
                      className="w-full bg-white border border-[#d1d9e6] rounded-lg px-3 py-2 text-sm text-[#1e3a5f] focus:outline-none focus:border-[#1e3a5f] placeholder-[#9ca3af]"
                      placeholder="KSP Crime Intelligence Brief" />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-[#6c757d] mb-1.5">Reference Period</label>
                    <input type="text" value={briefPeriod} onChange={e => setBriefPeriod(e.target.value)}
                      className="w-full bg-white border border-[#d1d9e6] rounded-lg px-3 py-2 text-sm text-[#1e3a5f] focus:outline-none focus:border-[#1e3a5f]" />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-[#6c757d] mb-1.5">Classification</label>
                    <select value={classification} onChange={e => setClassification(e.target.value as any)}
                      className="w-full bg-white border border-[#d1d9e6] rounded-lg px-3 py-2 text-sm text-[#1e3a5f] focus:outline-none focus:border-[#1e3a5f] cursor-pointer">
                      <option value="RESTRICTED">RESTRICTED</option>
                      <option value="CONFIDENTIAL">CONFIDENTIAL</option>
                      <option value="SECRET">SECRET</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-[#6c757d] mb-1.5">Approving Officer</label>
                    <input type="text" value={approvingOfficer} onChange={e => setApprovingOfficer(e.target.value)}
                      placeholder={role}
                      className="w-full bg-white border border-[#d1d9e6] rounded-lg px-3 py-2 text-sm text-[#1e3a5f] focus:outline-none focus:border-[#1e3a5f] placeholder-[#9ca3af]" />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-[#6c757d] mb-1.5">
                    Key Findings <span className="text-slate-600 font-normal">(one per line)</span>
                  </label>
                  <textarea value={customFindings} onChange={e => setCustomFindings(e.target.value)} rows={5}
                    placeholder={"Organized crime syndicate operating in 3 districts detected\nHawala transaction volume increased 34% in Q2\nBiometric match identified wanted fugitive near Silk Board"}
                    className="w-full bg-white border border-[#d1d9e6] rounded-lg px-3 py-2 text-sm text-[#1e3a5f] focus:outline-none focus:border-[#1e3a5f] resize-none placeholder-[#9ca3af] font-mono text-xs leading-relaxed" />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-[#6c757d] mb-1.5">
                    Recommendations <span className="text-slate-600 font-normal">(one per line)</span>
                  </label>
                  <textarea value={keyRecs} onChange={e => setKeyRecs(e.target.value)} rows={4}
                    placeholder={"Deploy additional patrol units to Bengaluru City hotspots\nIssue lookout notice for identified syndicate members\nInitiate financial investigation for hawala networks"}
                    className="w-full bg-white border border-[#d1d9e6] rounded-lg px-3 py-2 text-sm text-[#1e3a5f] focus:outline-none focus:border-[#1e3a5f] resize-none placeholder-[#9ca3af] font-mono text-xs leading-relaxed" />
                </div>
              </div>
            )}

            {/* Footer actions */}
            <div className="flex gap-3 px-6 py-4 border-t border-[#d1d9e6]">
              <button onClick={() => setPreviewMode(v => !v)}
                className="flex items-center gap-1.5 px-4 py-2.5 bg-white hover:bg-[#eef2f7] text-[#2d4a6f] font-semibold text-sm rounded-lg border border-[#d1d9e6] transition cursor-pointer">
                <Printer size={13} /> {previewMode ? 'Edit Form' : 'Preview'}
                <ChevronRight size={12} />
              </button>
              <button onClick={handleDownload} disabled={generating}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 bg-[#1e3a5f] hover:bg-[#1e3a5f]/90 disabled:bg-slate-700 text-white font-bold text-sm rounded-lg transition cursor-pointer">
                {generating ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
                {generating ? 'Generating PDF...' : 'Download Intelligence Brief'}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};
